# Site settings
title: Ishan Avasthi
description: A blog about Ishan Avasthi
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ishan Avasthi
user_description: Totally obsessed with Telegram Bots, Cloud and Web Apps.
user_title: Software Developer
email: ishan@hi2.in
twitter_username:  lorem_ipsum
github_username: Ishan-EXE
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
